<?php

namespace Database\Seeders;

use App\Models\ExamenComplementaire;
use App\Models\Type;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExamenComplementaireSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = date('Y-m-d H:i:s');

        $types = array(
            array('libelle' => 'OPH', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'ORL', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'STO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'GO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'CVL', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'PSYCHO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'URO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'NEURO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'EF', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'GAS', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'PNEU', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'ANAPATH', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'IM', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'HEMA', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'BAC', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'BIO', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'PAR', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'HOR', 'created_at' => $date, 'updated_at' => $date),
            array('libelle' => 'IMSER', 'created_at' => $date, 'updated_at' => $date)
        );

        foreach($types as $type){
            Type::create($type);
        }

        $examen_complementaires = array(
            array('id' => '1','slug' => 'OPH001','fr_description' => 'CHAMP VISUEL AUTOMATIQUE','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '2','slug' => 'OPH002','fr_description' => 'CHAMP VISUEL AUTOMATIQUE TOP','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '3','slug' => 'OPH003','fr_description' => 'CHAMP VISUEL DE GOLDMANN','reference' => 'OPH','prix' => '18750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '4','slug' => 'OPH004','fr_description' => 'CHIRURGIE DU NYSTAGMUS','reference' => 'OPH','prix' => '101250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '5','slug' => 'OPH005','fr_description' => 'CONTRÔLE ORTHOPTIQUE ISOLÉ','reference' => 'OPH','prix' => '3750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '6','slug' => 'OPH006','fr_description' => 'COURBE D-ADAPTATION À L’OBSCURITÉ','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '7','slug' => 'OPH007','fr_description' => 'COURBE DETONOMÈTRIE ÉLECTRONIQUE','reference' => 'OPH','prix' => '9000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '8','slug' => 'OPH008','fr_description' => 'ELECTRORÉTINOGRAPHIE','reference' => 'OPH','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '9','slug' => 'OPH009','fr_description' => 'EPREUVES DE PROVOCATION DANS LE GLAUCOME','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '10','slug' => 'OPH010','fr_description' => 'EVISCERATION','reference' => 'OPH','prix' => '90000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '11','slug' => 'OPH011','fr_description' => 'EXAMEN DE LA MOTILITÉ OCULAIRE','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '12','slug' => 'OPH012','fr_description' => 'EXAMEN SENSORIO-MOTEUR','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '13','slug' => 'OPH013','fr_description' => 'F.O (FOND D OEIL)','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '14','slug' => 'OPH014','fr_description' => 'FLUOROMÉTRIE','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '15','slug' => 'OPH015','fr_description' => 'FLUOROSCOPIE','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '16','slug' => 'OPH016','fr_description' => 'GONIOSCOPIE','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '17','slug' => 'OPH017','fr_description' => 'ORBITOMÈTRIE','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '18','slug' => 'OPH018','fr_description' => 'PACHIMETRIE','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '19','slug' => 'OPH019','fr_description' => 'PÉRIMÈTRIE SUIVIE','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '20','slug' => 'OPH020','fr_description' => 'RÉFRACTOMÉTRIE (RFMA)','reference' => 'OPH','prix' => '3750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '21','slug' => 'OPH021','fr_description' => 'RÉFRACTOMÉTRIE AVEC CYCLOPLÉGIE','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '22','slug' => 'OPH022','fr_description' => 'REMPLACEMENT DU VITRÉ PAR VOIE POSTÉRIEURE','reference' => 'OPH','prix' => '52500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '23','slug' => 'OPH023','fr_description' => 'RÉPARATION PLAIE PALPÉBRALE AVEC RECTION BORD LIBRE','reference' => 'OPH','prix' => '52500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '24','slug' => 'OPH024','fr_description' => 'RÉTINOGRAPHIE MYDRIATIQUE','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '25','slug' => 'OPH025','fr_description' => 'RÉTINOGRAPHIE NON MYDRIATIQUE ISOLÉE','reference' => 'OPH','prix' => '3750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '26','slug' => 'OPH026','fr_description' => 'ROTH 28 HUE','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '27','slug' => 'OPH027','fr_description' => 'SECTION DE BRIDES VITRÉENNES PAR VOIE ANTÉRIEURE','reference' => 'OPH','prix' => '30000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '28','slug' => 'OPH028','fr_description' => 'SKIACOPIE (SKIA)','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '29','slug' => 'OPH029','fr_description' => 'SUTURE DE PLAIES CUTANÉO-MUQUEUSES DES PAUPIÈRES','reference' => 'OPH','prix' => '48750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '30','slug' => 'OPH030','fr_description' => 'TEST DE COULEUR','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '31','slug' => 'OPH031','fr_description' => 'TEST DE LANTHONY','reference' => 'OPH','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '32','slug' => 'OPH032','fr_description' => 'TONOGRAPHIE AU TONOMÈTRE DE SCHIOTZ','reference' => 'OPH','prix' => '3750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '33','slug' => 'OPH033','fr_description' => 'TONOGRAPHIE AU TONOMÈTRE ÉLECTRONIQUE','reference' => 'OPH','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '34','slug' => 'OPH034','fr_description' => 'TRABÉCULECTOMIE','reference' => 'OPH','prix' => '112500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '35','slug' => 'OPH035','fr_description' => 'VISION DE COULEUR','reference' => 'OPH','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '36','slug' => 'ORL001','fr_description' => 'AUDIOGRAMME','reference' => 'ORL','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '37','slug' => 'ORL002','fr_description' => 'AUDIOMÉTR1E SPÉCIAL DE L’ENFANT','reference' => 'ORL','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '38','slug' => 'ORL003','fr_description' => 'AUDIOMETRIE TONALE','reference' => 'ORL','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '39','slug' => 'ORL004','fr_description' => 'BILAN DE LA PATHOLOGIE DU LANGAGE ORAL/ ÉCRIT','reference' => 'ORL','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '40','slug' => 'ORL005','fr_description' => 'BILAN FONCTIONNEL DE LA PHONATION','reference' => 'ORL','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '41','slug' => 'ORL006','fr_description' => 'BILAN PHONÉTIQUE DU LANGAGE','reference' => 'ORL','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '42','slug' => 'ORL007','fr_description' => 'BIOPSIE DU LARYNX + LARYNGOSCOPE DIRECTE EN SUSPENSION','reference' => 'ORL','prix' => '112500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '43','slug' => 'ORL008','fr_description' => 'BIOPSIE ORL (PRÉLÈVEMENT D\'ORGANE)','reference' => 'ORL','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '44','slug' => 'ORL009','fr_description' => 'BRONCHOSCOPIE','reference' => 'ORL','prix' => '33750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '45','slug' => 'ORL010','fr_description' => 'BRONCHOSCOPIES ITÉRATIVES','reference' => 'ORL','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '46','slug' => 'ORL011','fr_description' => 'CAVOSCOPIE (ENDOSCOPIE DU CAVUM)','reference' => 'ORL','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '47','slug' => 'ORL012','fr_description' => 'DÉPISTAGE DE LA SURDITÉ','reference' => 'ORL','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '48','slug' => 'ORL013','fr_description' => 'EXAMEN D’APTITUDE À L’ACQUISITION DU LANGAGE ORAL/ ÉCRIT','reference' => 'ORL','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '49','slug' => 'ORL014','fr_description' => 'EXAMEN LABYRINTHIQUE','reference' => 'ORL','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '50','slug' => 'ORL015','fr_description' => 'EXPLORATION CHIRURGICALE DE L’OREILLE MOYENNE','reference' => 'ORL','prix' => '90000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '51','slug' => 'ORL016','fr_description' => 'IMPEDANCEMETRIE + REFLEXES STAPEDIENS','reference' => 'ORL','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '52','slug' => 'ORL017','fr_description' => 'NASO- FIBROSCOPIE + BIOPSIE','reference' => 'ORL','prix' => '30000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '53','slug' => 'ORL018','fr_description' => 'NASO-FIBROSCOPIE','reference' => 'ORL','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '54','slug' => 'ORL019','fr_description' => 'PEA (AUDIO-ÉLECTROENCÉPHALOGRAMME)','reference' => 'ORL','prix' => '60000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '55','slug' => 'ORL020','fr_description' => 'PEA (POTENTIELS ÉVOQUÉS AUDITIFS) : ADULTE ET ENFANT > 8 ANS','reference' => 'ORL','prix' => '64500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '56','slug' => 'ORL021','fr_description' => 'PEA (POTENTIELS ÉVOQUÉS AUDITIFS) : ENFANT «. 8 ANS 1','reference' => 'ORL','prix' => '52500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '57','slug' => 'ORL022','fr_description' => 'RSOFIBROSCOPIE','reference' => 'ORL','prix' => '33750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '58','slug' => 'ORL023','fr_description' => 'RSOPHAGOSCOPIE','reference' => 'ORL','prix' => '33750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '59','slug' => 'ORL024','fr_description' => 'SINUSCOPIE','reference' => 'ORL','prix' => '112500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '60','slug' => 'ORL025','fr_description' => 'SINUSCOPIE + BIOPSIE','reference' => 'ORL','prix' => '135000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '61','slug' => 'ORL026','fr_description' => 'TESTS DE PROVOCATION PAR VOIE NASALE,','reference' => 'ORL','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '62','slug' => 'STO001','fr_description' => 'RADIOGRAPHIE','reference' => 'STO','prix' => '3750','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '63','slug' => 'STO002','fr_description' => 'RADIOGRAPHIE RÉTROALVÉOLAIRE','reference' => 'STO','prix' => '5250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '64','slug' => 'GO001','fr_description' => 'EXAMEN DU COL SOUS AG','reference' => 'GO','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '65','slug' => 'GO002','fr_description' => 'ECHOGRAPHIE MAMMAIRE','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '66','slug' => 'GO003','fr_description' => 'ECHOGRAPHIE ABDOMINO PELVIENNE','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '67','slug' => 'GO004','fr_description' => 'ECHOGRAPHIE DOPPLER OBSTETRICALE (T2 - T3)','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '68','slug' => 'GO005','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 - T3 GROSSE SIMPLE)','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '69','slug' => 'GO006','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 - T3 GROSSESSE MULTIPLE)','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '70','slug' => 'GO007','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 -T3 MORPHOLOGIQUE - RECHERCHE DES MALFORMATIONS','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '71','slug' => 'GO008','fr_description' => 'ECHOGRAPHIE PELVIENNE','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '72','slug' => 'GO009','fr_description' => 'ECHOGRAPHIE PELVIENNE (SUS PUBIENNE + ENDO VAGINALE)','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '73','slug' => 'GO010','fr_description' => 'ECHOGRAPHIE VESICO PROSTATIQUE COMPLEMENTAIRE','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '74','slug' => 'GO011','fr_description' => 'HYSTEROSONOGRAPHIE','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '75','slug' => 'GO012','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T1 GROSSESSE SIMPLE OU MULTIPLE)','reference' => 'GO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '76','slug' => 'CVL001','fr_description' => 'LAPAROSCOPIE AVEC BIOPSIE','reference' => 'CVL','prix' => '270000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '77','slug' => 'CVL002','fr_description' => 'LAPAROSCOPIE DIAGNOSTIC SIMPLE','reference' => 'CVL','prix' => '225000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '78','slug' => 'CVL003','fr_description' => 'ANUSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '79','slug' => 'CVL004','fr_description' => 'ANUSCOPIE AVEC BIOPSIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '80','slug' => 'CVL005','fr_description' => 'BREATH TEST_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '81','slug' => 'CVL006','fr_description' => 'COLOSCOPIE AU DELA DE L`ANGLE GAUCHE AVEC BIOPSIE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '82','slug' => 'CVL007','fr_description' => 'COLOSCOPIE AU DELA DE L\'ANGLE GAUCHE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '83','slug' => 'CVL008','fr_description' => 'COLOSCOPIE SANS BIOPSIE AVEC ANESTHESIE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '84','slug' => 'CVL009','fr_description' => 'COLOSCOPIE TOTALE AVEC BIOPSIE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '85','slug' => 'CVL010','fr_description' => 'COLOSCOPIE TOTALE AVEC BIOPSIE SOUS ANESTHESIE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '86','slug' => 'CVL011','fr_description' => 'ENDOSCOPIE OESO GASTRO DUODENALE AVEC BIOPSIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '87','slug' => 'CVL012','fr_description' => 'ENDOSCOPIE OESO GASTRO DUODENALE AVEC TEST A L\'UREASE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '88','slug' => 'CVL013','fr_description' => 'PH METRIE OESOPHAGIENNE DES 24H','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '89','slug' => 'CVL014','fr_description' => 'RECTOSIGMOÏDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '90','slug' => 'CVL015','fr_description' => 'RECTOSIGMOÏDOSCOPIE AVEC BIOPSIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '91','slug' => 'CVL016','fr_description' => 'COLOSCOPIE TOTALE SANS BIOPSIE_ENDOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '92','slug' => 'CVL017','fr_description' => 'ENDOSCOPIE OESO GASTRO DUODENALE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '93','slug' => 'CVL018','fr_description' => 'OESOPHAGOSCOPIE','reference' => 'CVL','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '94','slug' => 'PSYCHO001','fr_description' => 'TEST ECHELLE D\'ESTIME DE SOI','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '95','slug' => 'PSYCHO002','fr_description' => 'TEST ECHELLE D\'ANXIETE','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '96','slug' => 'PSYCHO003','fr_description' => 'TEST ECHELLE DE DEPRESSION','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '97','slug' => 'PSYCHO004','fr_description' => 'TEST ECHELLE DE TRAUMA','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '98','slug' => 'PSYCHO005','fr_description' => 'TEST ECHELLE DE BECK','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '99','slug' => 'PSYCHO006','fr_description' => 'SOUTIEN PSYCHOLOGIQUE','reference' => 'PSYCHO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '100','slug' => 'URO001','fr_description' => 'CYSTOSCOPIE DIAGNOSTIQUE','reference' => 'URO','prix' => '67500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '101','slug' => 'URO002','fr_description' => 'DÉBITMÉTRIE,','reference' => 'URO','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '102','slug' => 'URO003','fr_description' => 'ÉTUDE URODYNAMIQUE DU BAS APPAREIL URINAIRE','reference' => 'URO','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '103','slug' => 'URO004','fr_description' => 'ECHOGRAPHIE ABDOMINO PELVIENNE + PROSTATE','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '104','slug' => 'URO005','fr_description' => 'ECHOGRAPHIE DES VOIES URINAIRES','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '105','slug' => 'URO006','fr_description' => 'ECHOGRAPHIE DOPPLER PENIENNE','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '106','slug' => 'URO007','fr_description' => 'ECHOGRAPHIE VESICO PROSTATIQUE','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '107','slug' => 'URO008','fr_description' => 'ECHOGRAPHIE VESICO PROSTATIQUE COMPLEMENTAIRE','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '108','slug' => 'URO009','fr_description' => 'ECHOGRAPHIE DOPPLER DES ARTERES RENALES','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '109','slug' => 'URO010','fr_description' => 'BIOPSIE PROSTATIQUE ECHO GUIDEE','reference' => 'URO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '110','slug' => 'NEURO001','fr_description' => 'ELECTROENCEPHALOGRAMME STANDARD','reference' => 'NEURO','prix' => '67500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '111','slug' => 'NEURO002','fr_description' => 'ELECTROENCEPHALOGRAMME LONGUE DUREE','reference' => 'NEURO','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '112','slug' => 'NEURO003','fr_description' => 'ELECTROMYOGRAPHIE','reference' => 'NEURO','prix' => '22500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '113','slug' => 'NEURO004','fr_description' => 'ELECTROMYOGRAPHIE 4 MEMBRES','reference' => 'NEURO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '114','slug' => 'NEURO005','fr_description' => 'PONCTION LOMBAIRE','reference' => 'NEURO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '115','slug' => 'NEURO006','fr_description' => 'ELECTROMYOGRAPHIE_LAMAT','reference' => 'NEURO','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '116','slug' => 'EF001','fr_description' => 'échocardiographie transthoracique','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '117','slug' => 'EF002','fr_description' => 'échocardiographie transoesophagienne','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '118','slug' => 'EF003','fr_description' => 'échocardiographie d’effort sur bicyclette ergonomique','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '119','slug' => 'EF004','fr_description' => 'épreuve d’effort sur bicyclette ergonomique','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '120','slug' => 'EF005','fr_description' => 'épreuve d’effort sur tapis roulant','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '121','slug' => 'EF006','fr_description' => 'échocardiographie de stress','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '122','slug' => 'EF007','fr_description' => 'épreuve d’effort métabolique sur bicyclette ergonomique','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '123','slug' => 'EF008','fr_description' => 'Holter rythmique de 24 h','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '124','slug' => 'EF009','fr_description' => 'Holter rythmique de 72 h','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '125','slug' => 'EF010','fr_description' => 'MAPA - Mesure Ambulatoire de la Pression Artérielle','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '126','slug' => 'EF011','fr_description' => 'Tilt test','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '127','slug' => 'EF012','fr_description' => 'ECG STANDARD','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '128','slug' => 'EF013','fr_description' => 'ECG D`EFFORT','reference' => 'EF','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '129','slug' => 'GAS001 ','fr_description' => 'ANUSCOPIE ','reference' => 'GAS','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '130','slug' => 'GAS002','fr_description' => 'ANUSCOPIE + LIGATURE DES HÉMORROÏDES PAR SEANCE ','reference' => 'GAS','prix' => '7500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '131','slug' => 'GAS003','fr_description' => 'BIOPSIE EN ENDOSCOPIE ','reference' => 'GAS','prix' => '10000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '132','slug' => 'GAS004','fr_description' => 'COLOSCOPIE GAUCHE ','reference' => 'GAS','prix' => '41250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '133','slug' => 'GAS005','fr_description' => 'COLOSCOPIE TOTALE ','reference' => 'GAS','prix' => '71250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '134','slug' => 'GAS006','fr_description' => 'COLOSCOPIE TOTALE + POLYPECTOMIE ','reference' => 'GAS','prix' => '75000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '135','slug' => 'GAS007','fr_description' => 'FIBROSCOPIE ','reference' => 'GAS','prix' => '41250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '136','slug' => 'GAS008','fr_description' => 'FIBROSCOPIE + EXTRACTION DES CORPS ÉTRANGERS ','reference' => 'GAS','prix' => '56250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '137','slug' => 'GAS009','fr_description' => 'FIBROSCOPIE + LIGATURE DES VARICES OESOPHAGIENNES ','reference' => 'GAS','prix' => '56250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '138','slug' => 'GAS011','fr_description' => 'RECTOSCOPIE ','reference' => 'GAS','prix' => '11250','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '139','slug' => 'GAS012','fr_description' => 'RECTOSIGMOIDOSCOPIE ','reference' => 'GAS','prix' => '21000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '140','slug' => 'PNEU001','fr_description' => 'FIBROSCOPIE','reference' => 'PNEU','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '141','slug' => 'PNEU002','fr_description' => 'BIOPSIE PLEURALE','reference' => 'PNEU','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '142','slug' => 'PNEU003','fr_description' => 'SPIROMETRIE','reference' => 'PNEU','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '143','slug' => 'ANAPATH001','fr_description' => 'BIOPSIE DU COL SOUS COLPOSCOPIE','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '144','slug' => 'ANAPATH002','fr_description' => 'CYTOLOGIE GENERALE (ASCITE, LIQUIDE PLEURAL, ETC..)','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '145','slug' => 'ANAPATH003','fr_description' => 'CYTOPONCTION A L\'AIGUILLE + ANALYSE/SEIN','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '146','slug' => 'ANAPATH004','fr_description' => 'BIOPSIE POLYPE','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '147','slug' => 'ANAPATH005','fr_description' => 'BIOPSIE STANDARD','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '148','slug' => 'ANAPATH006','fr_description' => 'EXAMEN ANATOMOPATHOGIE : HISTOLOGIE','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '149','slug' => 'ANAPATH007','fr_description' => 'CYTOPONCTION MAMMAIRE BILATERALE PAR OPPOSITION DES LAMES','reference' => 'ANAPATH','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '150','slug' => 'IM001','fr_description' => 'AGE OSSEUX < 16 ANS','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '151','slug' => 'IM002','fr_description' => 'RX BASSIN + HANCHES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '152','slug' => 'IM003','fr_description' => 'RX EPAULE : 3 - 4 INCIDENCES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '153','slug' => 'IM004','fr_description' => 'RX MEMBRES INFERIEUR 1 SEGMENT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '154','slug' => 'IM005','fr_description' => 'RX MEMBRES INFERIEURS 2 SEGMENTS','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '155','slug' => 'IM006','fr_description' => 'RX MEMBRES INFERIEURS TELEMETRIE ( PANGONOMETRIE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '156','slug' => 'IM007','fr_description' => 'RX MEMBRES SUPERIEURS 1 SEGMENT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '157','slug' => 'IM008','fr_description' => 'RX MEMBRES SUPERIEURS 2 SEGMENTS','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '158','slug' => 'IM009','fr_description' => 'RX 2 EPAULES : 3 - 4 INCIDENCES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '159','slug' => 'IM010','fr_description' => 'RX ARTHORGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '160','slug' => 'IM011','fr_description' => 'RX ASP','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '161','slug' => 'IM012','fr_description' => 'RX CAVOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '162','slug' => 'IM013','fr_description' => 'RX CRANE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '163','slug' => 'IM014','fr_description' => 'RX CYSTOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '164','slug' => 'IM015','fr_description' => 'RX DEFERENTOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '165','slug' => 'IM016','fr_description' => 'RX FISTULOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '166','slug' => 'IM017','fr_description' => 'RX GALACTOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '167','slug' => 'IM018','fr_description' => 'RX HYSTEROSALPINGOGRAPHIE AVEC KIT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '168','slug' => 'IM019','fr_description' => 'RX HYSTEROSALPINGOGRAPHIE SANS KIT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '169','slug' => 'IM020','fr_description' => 'RX LARYNGOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '170','slug' => 'IM021','fr_description' => 'RX LAVEMENT BARYTE AU HYDRO SOLUBLES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '171','slug' => 'IM022','fr_description' => 'RX LAVEMENT BARYTE DOUBLE CONTRASTE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '172','slug' => 'IM023','fr_description' => 'RX LAVEMENT BARYTE MONO CONTRASTE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '173','slug' => 'IM024','fr_description' => 'RX LAVEMENT BAYTE REDUCTION HYDROSTATIQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '174','slug' => 'IM025','fr_description' => 'RX MAMMOGRAPHIE + GALACTOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '175','slug' => 'IM026','fr_description' => 'RX MAMMOGRAPHIE DEPISTAGE : 2 INCIDENCES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '176','slug' => 'IM027','fr_description' => 'RX MAMMOGRAPHIE DIAGNOSTIC : 3 INCIDENCES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '177','slug' => 'IM028','fr_description' => 'RX MYELOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '178','slug' => 'IM029','fr_description' => 'RX PANORAMIQUE DENTAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '179','slug' => 'IM030','fr_description' => 'RX PHLEBOGRAPHIE BILATERALE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '180','slug' => 'IM031','fr_description' => 'RX RACHIS CERVICAL','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '181','slug' => 'IM032','fr_description' => 'RX RACHIS CERVICO-DORSA','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '182','slug' => 'IM033','fr_description' => 'RX RACHIS CERVICO-DORSO-LOMBAIRE COMPLET','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '183','slug' => 'IM034','fr_description' => 'RX RACHIS CERVICO-LOMBAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '184','slug' => 'IM035','fr_description' => 'RX RACHIS DORSAL','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '185','slug' => 'IM036','fr_description' => 'RX RACHIS DORSO - LOMBAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '186','slug' => 'IM037','fr_description' => 'RX RACHIS LOMBAIRE (DE SEZE + PROFIL)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '187','slug' => 'IM038','fr_description' => 'RX RACHIS LOMBAIRE + HANCHE + BASSIN','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '188','slug' => 'IM039','fr_description' => 'RX SIALOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '189','slug' => 'IM040','fr_description' => 'RX TELECRANE + PROFIL + MESURES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '190','slug' => 'IM041','fr_description' => 'Rx TELERACHIS + MESURES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '191','slug' => 'IM042','fr_description' => 'RX THORAX OSSEUX','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '192','slug' => 'IM043','fr_description' => 'RX THORAX PULMONAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '193','slug' => 'IM044','fr_description' => 'RX TRANSIT DU GRELE (T.G)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '194','slug' => 'IM045','fr_description' => 'RX TRANSIT OESO GASTRO DUODENAL','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '195','slug' => 'IM046','fr_description' => 'RX TRANSIT OESOPHAGIEN (T.O)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '196','slug' => 'IM047','fr_description' => 'RX UROGRAPHIE INTRA VEINEUSE + MICTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '197','slug' => 'IM048','fr_description' => 'SACCORADICULOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '198','slug' => 'IM049','fr_description' => 'RX BASSIN + HANCHES (COXOMETRIE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '199','slug' => 'IM050','fr_description' => 'INFILTRATION RADIO GUIDEE_RADIOLOGIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '200','slug' => 'IM051','fr_description' => 'ANGIO SCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '201','slug' => 'IM052','fr_description' => 'ARTHROSCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '202','slug' => 'IM053','fr_description' => 'BIOPSIE - PONCTION, DRAINAGE SOUS TDM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '203','slug' => 'IM054','fr_description' => 'COLO SCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '204','slug' => 'IM055','fr_description' => 'SCANNER THORACIQUE AVEC INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '205','slug' => 'IM056','fr_description' => 'SCANNER THORACIQUE SANS INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '206','slug' => 'IM057','fr_description' => 'DENTA SCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '207','slug' => 'IM058','fr_description' => 'MYELOSCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '208','slug' => 'IM059','fr_description' => 'PELVISCANNER - PELVIMETRIE TDM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '209','slug' => 'IM060','fr_description' => 'SCANNER AVEC INJECTION PAR SEGMENT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '210','slug' => 'IM061','fr_description' => 'SCANNER CEREBRAL PEDIATRIQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '211','slug' => 'IM062','fr_description' => 'SCANNER CORPS ENTIER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '212','slug' => 'IM063','fr_description' => 'SCANNER PEDIATRIQUE PAR SEGMENT AVEC OU SANS INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '213','slug' => 'IM064','fr_description' => 'SCANNER SANS INJECTION PAR SEGMENT','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '214','slug' => 'IM065','fr_description' => 'SCANNER SINUS SANS INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '215','slug' => 'IM066','fr_description' => 'URO SCANNER AVEC INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '216','slug' => 'IM067','fr_description' => 'URO SCANNER SANS INJECTION','reference' => 'IM','prix' => '100500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '217','slug' => 'IM068','fr_description' => 'CORO- SCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '218','slug' => 'IM069','fr_description' => 'INFILTRATION SCANNO GUIDEE_SCANNER','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '219','slug' => 'IM070','fr_description' => 'SCANNER AVEC INJECTION PAR SEGMENT (CML)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '220','slug' => 'IM071','fr_description' => 'BIOPSIE OSSEUSE SOUS TDM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '221','slug' => 'IM072','fr_description' => 'IRM SANS INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '222','slug' => 'IM073','fr_description' => 'IRM AVEC INJECTION','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '223','slug' => 'IM074','fr_description' => 'MYELO IRM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '224','slug' => 'IM075','fr_description' => 'PHLEBO IRM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '225','slug' => 'IM076','fr_description' => 'COLO IRM - ENTERO IRM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '226','slug' => 'IM077','fr_description' => 'BILI IRM','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '227','slug' => 'IM078','fr_description' => 'IRM HEPATIQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '228','slug' => 'IM079','fr_description' => 'IRM PROSTATIQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '229','slug' => 'IM080','fr_description' => 'IRM PELVIS FEMININ','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '230','slug' => 'IM081','fr_description' => 'IRM TSA','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '231','slug' => 'IM082','fr_description' => 'IRM CARDIAQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '232','slug' => 'IM083','fr_description' => 'IRM ORL (PAROTIDE, SALIVAIRE, CAVUM, LARYNX, OREILLE, SINUS)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '233','slug' => 'IM084','fr_description' => 'IRM AORTE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '234','slug' => 'IM085','fr_description' => 'IRM FOETALE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '235','slug' => 'IM086','fr_description' => 'IRM ABDOMINALE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '236','slug' => 'IM087','fr_description' => 'IRM MEDULLAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '237','slug' => 'IM088','fr_description' => 'IRM MAMMAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '238','slug' => 'IM089','fr_description' => 'BIOPSIE ECHO GUIDEE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '239','slug' => 'IM090','fr_description' => 'ECHOGRAPHIE MAMMAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '240','slug' => 'IM091','fr_description' => 'ECHOGRAPHIE ABDOMINALE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '241','slug' => 'IM092','fr_description' => 'ECHOGRAPHIE ABDOMINO PELVIENNE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '242','slug' => 'IM093','fr_description' => 'ECHOGRAPHIE ABDOMINO PELVIENNE + PROSTATE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '243','slug' => 'IM094','fr_description' => 'ECHOGRAPHIE DES PARTIES MOLLES ET PETITS ORGANES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '244','slug' => 'IM095','fr_description' => 'ECHOGRAPHIE DES VOIES URINAIRES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '245','slug' => 'IM096','fr_description' => 'ECHOGRAPHIE DOPPLER ARTERIEL ET VEINEUX','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '246','slug' => 'IM097','fr_description' => 'ECHOGRAPHIE DOPPLER ARTERIEL OU VEINEUX','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '247','slug' => 'IM098','fr_description' => 'ECHOGRAPHIE DOPPLER DES VAISSEAUX DU COU','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '248','slug' => 'IM099','fr_description' => 'ECHOGRAPHIE DOPPLER OBSTETRICALE (T2 - T3)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '249','slug' => 'IM100','fr_description' => 'ECHOGRAPHIE DOPPLER PENIENNE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '250','slug' => 'IM101','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 - T3 GROSSE SIMPLE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '251','slug' => 'IM102','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 - T3 GROSSESSE MULTIPLE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '252','slug' => 'IM103','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T2 -T3 MORPHOLOGIQUE - RECHERCHE DES MALFORMATIONS','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '253','slug' => 'IM104','fr_description' => 'ECHOGRAPHIE PELVIENNE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '254','slug' => 'IM105','fr_description' => 'ECHOGRAPHIE PELVIENNE (SUS PUBIENNE + ENDO VAGINALE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '255','slug' => 'IM106','fr_description' => 'ECHOGRAPHIE VESICO PROSTATIQUE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '256','slug' => 'IM107','fr_description' => 'ECHOGRAPHIE VESICO PROSTATIQUE COMPLEMENTAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '257','slug' => 'IM108','fr_description' => 'HYSTEROSONOGRAPHIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '258','slug' => 'IM109','fr_description' => 'ECHOGRAPHIE DOPPLER DES ARTERES RENALES','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '259','slug' => 'IM110','fr_description' => 'ECHOGRAPHIE OBSTETRICALE (T1 GROSSESSE SIMPLE OU MULTIPLE)','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '260','slug' => 'IM111','fr_description' => 'BIOPSIE PROSTATIQUE ECHO GUIDEE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '261','slug' => 'IM112','fr_description' => 'ELASTOMETRIE DU FOIE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '262','slug' => 'IM113','fr_description' => 'ECHOGRAPHIE OSTEO ARTICULAIRE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '263','slug' => 'IM114','fr_description' => 'CYTOPONCTION ECHO GUIDEE','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '264','slug' => 'IM115','fr_description' => 'ECHOGRAPHIE DOPPLER DES VAISSEAUX DU COU','reference' => 'IM','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '265','slug' => 'HEMA001','fr_description' => 'COOMBS DIRECT','reference' => 'HEMA','prix' => '5600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '266','slug' => 'HEMA002','fr_description' => 'COOMBS INDIRECT','reference' => 'HEMA','prix' => '5600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '267','slug' => 'HEMA003','fr_description' => 'DU','reference' => 'HEMA','prix' => '5600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '268','slug' => 'HEMA004','fr_description' => 'ELECTROPHORÈSES D’HÉMOGLOBINE ELHB','reference' => 'HEMA','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '269','slug' => 'HEMA005','fr_description' => 'FROTTIS DU MYELOGRAMME','reference' => 'HEMA','prix' => '5000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '270','slug' => 'HEMA006','fr_description' => 'FROTTIS SANGUIN','reference' => 'HEMA','prix' => '3000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '271','slug' => 'HEMA007','fr_description' => 'GROUPE SANGUIN/ RHÉSUS (GS/RH)','reference' => 'HEMA','prix' => '4760','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '272','slug' => 'HEMA008','fr_description' => 'INR','reference' => 'HEMA','prix' => '4800','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '273','slug' => 'HEMA009','fr_description' => 'NUMÉRATION FORMULE SANGUINE (NFS)','reference' => 'HEMA','prix' => '5600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '274','slug' => 'HEMA010','fr_description' => 'TAUX DE RETICULOCYTES','reference' => 'HEMA','prix' => '5000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '275','slug' => 'HEMA011','fr_description' => 'TCA OU TCK','reference' => 'HEMA','prix' => '4800','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '276','slug' => 'HEMA012','fr_description' => 'TP','reference' => 'HEMA','prix' => '4800','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '277','slug' => 'HEMA013','fr_description' => 'TP, INR ET TCA OU TCK','reference' => 'HEMA','prix' => '9600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '278','slug' => 'HEMA014','fr_description' => 'VITESSE DE SÉDIMENTATION (VS)','reference' => 'HEMA','prix' => '2800','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '279','slug' => 'BAC001','fr_description' => 'BAAR','reference' => 'BAC','prix' => '6000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '280','slug' => 'BAC002','fr_description' => 'BANDELETTE URINAIRE COMBI 11','reference' => 'BAC','prix' => '3000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '281','slug' => 'BAC003','fr_description' => 'ECBU+ ATB','reference' => 'BAC','prix' => '11200','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '282','slug' => 'BAC004','fr_description' => 'EXAMEN CYTOLOGIE DES LIQUIDES DE PONCTIONS','reference' => 'BAC','prix' => '11200','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '283','slug' => 'BAC005','fr_description' => 'G TEST','reference' => 'BAC','prix' => '4000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '284','slug' => 'BAC006','fr_description' => 'GLYCÉMIE À JEUN (GLUCOMÈTRE)','reference' => 'BAC','prix' => '1000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '285','slug' => 'BAC007','fr_description' => 'MYCOPLASME','reference' => 'BAC','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '286','slug' => 'BAC008','fr_description' => 'PU + ATB','reference' => 'BAC','prix' => '11200','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '287','slug' => 'BAC009','fr_description' => 'SPERMOCULTURE','reference' => 'BAC','prix' => '11200','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '288','slug' => 'BAC010','fr_description' => 'Pcv','reference' => 'BAC','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '289','slug' => 'BAC011','fr_description' => 'Pu','reference' => 'BAC','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '290','slug' => 'BAC012','fr_description' => 'Pcv + atb','reference' => 'BAC','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '291','slug' => 'BAC013','fr_description' => 'SPERMOGRAMME','reference' => 'BAC','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '292','slug' => 'BIO001','fr_description' => 'ACIDE URIQUE','reference' => 'BIO','prix' => '3600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '293','slug' => 'BIO002','fr_description' => 'ALAT (GPT)','reference' => 'BIO','prix' => '3000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '294','slug' => 'BIO003','fr_description' => 'ALBUMINÉMIE','reference' => 'BIO','prix' => '5500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '295','slug' => 'BIO004','fr_description' => 'ALBUMINURIE','reference' => 'BIO','prix' => '5500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '296','slug' => 'BIO005','fr_description' => 'ASAT (GOT)','reference' => 'BIO','prix' => '3000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '297','slug' => 'BIO006','fr_description' => 'BILAN LIPIDIQUE','reference' => 'BIO','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '298','slug' => 'BIO007','fr_description' => 'BILIRUBINE DIRECTE','reference' => 'BIO','prix' => '4760','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '299','slug' => 'BIO008','fr_description' => 'BILIRUBINE TOTALE','reference' => 'BIO','prix' => '4760','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '300','slug' => 'BIO009','fr_description' => 'CHIMIE DES LIQUIDES DE PONCTION','reference' => 'BIO','prix' => '7000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '301','slug' => 'BIO010','fr_description' => 'CHLORE','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '302','slug' => 'BIO011','fr_description' => 'CL) CALCIUM','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '303','slug' => 'BIO012','fr_description' => 'COPROLOGIE OU SELLES +TECHNIQUES DE CONCENTRATION','reference' => 'BIO','prix' => '2000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '304','slug' => 'BIO013','fr_description' => 'CRÉATININE','reference' => 'BIO','prix' => '3640','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '305','slug' => 'BIO014','fr_description' => 'ELECTROPHORÉSE DES PROTÉINES','reference' => 'BIO','prix' => '18000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '306','slug' => 'BIO015','fr_description' => 'GAMMA GT (GGT)','reference' => 'BIO','prix' => '3920','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '307','slug' => 'BIO016','fr_description' => 'GE','reference' => 'BIO','prix' => '2000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '308','slug' => 'BIO017','fr_description' => 'HÉMOGLOBINE GLYQUÉE','reference' => 'BIO','prix' => '12000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '309','slug' => 'BIO018','fr_description' => 'IONOGRAMME SANGUIN SIMPLE (NA, K,','reference' => 'BIO','prix' => '9600','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '310','slug' => 'BIO019','fr_description' => 'IONOGRAMME SANGUIN SIMPLE (NA, K,CL,CA,MG)','reference' => 'BIO','prix' => '16000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '311','slug' => 'BIO020','fr_description' => 'MAGNÉSIUM','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '312','slug' => 'BIO021','fr_description' => 'PHOSPHATASE ALCALINE (PAL)','reference' => 'BIO','prix' => '4000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '313','slug' => 'BIO022','fr_description' => 'PHOSPHORE','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '314','slug' => 'BIO023','fr_description' => 'POTASSIUM','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '315','slug' => 'BIO024','fr_description' => 'PROTÉINE DE 24H','reference' => 'BIO','prix' => '5000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '316','slug' => 'BIO025','fr_description' => 'PROTÉINÉMIE (PROTÉINE TOTALE)','reference' => 'BIO','prix' => '5000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '317','slug' => 'BIO026','fr_description' => 'SODIUM','reference' => 'BIO','prix' => '3500','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '318','slug' => 'BIO027','fr_description' => 'URÉE','reference' => 'BIO','prix' => '3640','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '319','slug' => 'PAR001','fr_description' => 'CULOT URINAIRE','reference' => 'PAR','prix' => '2000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '320','slug' => 'PAR002','fr_description' => 'D-DIMERES','reference' => 'PAR','prix' => '20000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '321','slug' => 'PAR003','fr_description' => 'RECHERCHE DES MICROFILAIRES (RMF)','reference' => 'PAR','prix' => '6720','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '322','slug' => 'PAR004','fr_description' => 'SANG OCCULTRE','reference' => 'PAR','prix' => '10000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '323','slug' => 'PAR005','fr_description' => 'SKIN-SNIP TEST','reference' => 'PAR','prix' => '4480','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '324','slug' => 'PAR007','fr_description' => 'TDR PALUDISME','reference' => 'PAR','prix' => '1000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '325','slug' => 'HOR001','fr_description' => 'Oestradiol (E2)','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '326','slug' => 'HOR002','fr_description' => 'FSH','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '327','slug' => 'HOR003','fr_description' => 'LH','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '328','slug' => 'HOR004','fr_description' => 'PROLACTINE LIBRE','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '329','slug' => 'HOR005','fr_description' => 'PSA','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '330','slug' => 'HOR006','fr_description' => 'T3 TOTALE','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '331','slug' => 'HOR007','fr_description' => 'T4 LIBRE','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '332','slug' => 'HOR008','fr_description' => 'TESTOSTÉRONE','reference' => 'HOR','prix' => '18000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '333','slug' => 'HOR009','fr_description' => 'Β-HCG','reference' => 'HOR','prix' => '15000','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '334','slug' => 'HOR010','fr_description' => 'PSA TOTAL','reference' => 'HOR','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '335','slug' => 'HOR011','fr_description' => 'PSA LIBRE','reference' => 'HOR','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '336','slug' => 'HOR012','fr_description' => 'NT-PRO BNP','reference' => 'HOR','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '337','slug' => 'HOR013','fr_description' => 'CTNI /MYO/CKMB','reference' => 'HOR','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '338','slug' => 'IMSER001','fr_description' => 'Protéine C réactive (CRP)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '339','slug' => 'IMSER002','fr_description' => 'Antistreptolysine O (ASLO)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '340','slug' => 'IMSER003','fr_description' => 'Facteur rhumatoïde (FR)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '341','slug' => 'IMSER004','fr_description' => 'Widal & Félix sur plaque','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '342','slug' => 'IMSER005','fr_description' => 'Hépatite B (Aghbs dépistage)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '343','slug' => 'IMSER006','fr_description' => 'Hépatite B confirmation','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '344','slug' => 'IMSER007','fr_description' => 'Hépatite C (AcHCV dépistage)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '345','slug' => 'IMSER008','fr_description' => 'Hépatite C confirmation','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '346','slug' => 'IMSER009','fr_description' => 'Hiv (dépistage)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '347','slug' => 'IMSER010','fr_description' => 'Hiv (confirmation)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '348','slug' => 'IMSER011','fr_description' => 'Chlamydia Direct','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '349','slug' => 'IMSER012','fr_description' => 'Chlamydia qualitatif IgM','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '350','slug' => 'IMSER013','fr_description' => 'Syphilis (Tpha/Vdrl ou RPR)','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '351','slug' => 'IMSER014','fr_description' => 'Chlamydia IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '352','slug' => 'IMSER015','fr_description' => 'Chlamydia IgG elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '353','slug' => 'IMSER016','fr_description' => 'Chlamydia IgG+IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '354','slug' => 'IMSER017','fr_description' => 'Toxoplasmose IgG/IgM qualitatif','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '355','slug' => 'IMSER018','fr_description' => 'Toxoplasmose IgG elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '356','slug' => 'IMSER019','fr_description' => 'Toxoplasmose IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '357','slug' => 'IMSER020','fr_description' => 'Toxoplasmose IgG+IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '358','slug' => 'IMSER021','fr_description' => 'Rubéole IgG/IgM qualitatif','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '359','slug' => 'IMSER022','fr_description' => 'Rubeole IgG elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '360','slug' => 'IMSER023','fr_description' => 'Rubeole IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '361','slug' => 'IMSER024','fr_description' => 'Rubeole IgG + IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '362','slug' => 'IMSER023','fr_description' => 'Rubeole IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL),
            array('id' => '363','slug' => 'IMSER024','fr_description' => 'Rubeole IgG + IgM elisa','reference' => 'IMSER','prix' => '0','created_at' => NULL,'updated_at' => NULL,'deleted_at' => NULL)
        );

        foreach($examen_complementaires as $examen_complementaire){
            $new_examen_complementaire = ExamenComplementaire::create(['id' => $examen_complementaire['id'], 'fr_description' => $examen_complementaire['fr_description'], 'prix' => $examen_complementaire['prix'] ?? 0, 'slug' => $examen_complementaire['slug'], 'created_at' => $examen_complementaire['created_at'], 'updated_at' => $examen_complementaire['updated_at'], 'deleted_at' => $examen_complementaire['deleted_at']]);
            $type = Type::where('libelle', $examen_complementaire['reference'])->first();
            $new_examen_complementaire->types()->sync($type);
        }
    }
}
